# Generated by Django 5.2.14 on 2026-07-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seating_type', models.CharField(choices=[('labeled', 'Labeled seating'), ('general', 'General admission')], max_length=20)),
                ('rows', models.PositiveIntegerField(blank=True, null=True)),
                ('columns', models.PositiveIntegerField(blank=True, null=True)),
                ('label_style', models.CharField(blank=True, choices=[('alpha_numeric', 'Letter rows, numbered seats (A1, A2...)'), ('numeric', 'Numbered rows and seats (1-1, 1-2...)')], max_length=20, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='venues.venue')),
            ],
            options={
                'ordering': ['venue', 'name'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'name'), name='unique_space_name_per_venue')],
            },
        ),
    ]
