# Generated by Django 5.2.16 on 2026-07-24 16:41

from django.db import migrations

# Duplicated from users.signals rather than imported — migrations must stay
# frozen in time; importing live constants would make this migration's
# behavior silently depend on future edits to signals.py.
ORGANIZER_GROUP_NAME = "Organizers"
ORGANIZER_PERMISSION_CODENAMES = [
    "add_event", "change_event", "delete_event", "view_event",
    "add_seat", "change_seat", "delete_seat", "view_seat",
]


def seed_organizer_group(apps, schema_editor):
    """One-time backfill — users.signals.sync_organizer_group only fires on
    future User.save() calls, so any organizer created before this signal
    existed needs to be added to the group here instead."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("users", "User")

    group, created = Group.objects.get_or_create(name=ORGANIZER_GROUP_NAME)
    if created:
        permissions = Permission.objects.filter(
            content_type__app_label="events",
            codename__in=ORGANIZER_PERMISSION_CODENAMES,
        )
        group.permissions.set(permissions)

    for user in User.objects.filter(role="ORGANIZER"):
        user.groups.add(group)


def unseed_organizer_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=ORGANIZER_GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
        ('events', '0005_event_is_archived'),
    ]

    operations = [
        migrations.RunPython(seed_organizer_group, unseed_organizer_group),
    ]
