# Generated by Django 5.2.16 on 2026-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_space_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='display_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(condition=models.Q(('column__isnull', False), ('row__isnull', False)), fields=('event', 'row', 'column'), name='unique_grid_position_per_event'),
        ),
    ]
