# Generated by Django 5.2.16 on 2026-08-09 11:36

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_enable_pg_trgm'),
        ('venues', '0002_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='event_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
