# Generated by Django 5.2.16 on 2026-07-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_archived'),
        ('knowledge', '0003_knowledgechunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='events.event'),
        ),
    ]
