# Generated by Django 5.2.12 on 2026-04-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
