# Generated by Django 5.2.16 on 2026-07-10 19:45

import ai_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbooking',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=ai_assistant.models.get_pending_action_expiry),
        ),
    ]
