# Generated by Django 5.2.16 on 2026-07-17 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_pendingbookingcancellation'),
        ('bookings', '0005_bookingseat_unique_seat_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_retries', to='bookings.booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_retry_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
