# Generated by Django 5.2.16 on 2026-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_usagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='system_prompt_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
