# Generated by Django 5.2.16 on 2026-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_usagelog_system_prompt_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='tool_called',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
