# Generated by Django 5.2.16 on 2026-07-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_pendingbookingthread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpaymentretry',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='pendingpaymentretry',
            name='user',
        ),
        migrations.DeleteModel(
            name='PendingBooking',
        ),
        migrations.DeleteModel(
            name='PendingPaymentRetry',
        ),
    ]
