# Generated by Django 5.2.16 on 2026-07-27 14:47

import ai_assistant.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_remove_pendingpaymentretry_booking_and_more'),
        ('bookings', '0006_remove_bookingseat_unique_seat_claim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPaymentRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=ai_assistant.models.get_pending_action_expiry)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_retries', to='bookings.booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
