from django import forms
from django.contrib import admin

from events.models import Event
from core.admin_widgets import ChainedSelect
from knowledge.models import KnowledgeDocument, KnowledgeChunk


class EventSelect(ChainedSelect):
    """Only offer Events belonging to whichever Venue is currently
    selected — events with no venue at all are correctly hidden once a
    venue is chosen, and everything shows again if venue is cleared."""
    parent_field_id = "id_venue"

    def get_parent_map(self):
        return dict(Event.objects.values_list("id", "venue_id"))


class KnowledgeDocumentAdminForm(forms.ModelForm):
    class Meta:
        model = KnowledgeDocument
        fields = "__all__"
        widgets = {"event": EventSelect}


@admin.register(KnowledgeDocument)
class KnowledgeDocumentAdmin(admin.ModelAdmin):
    form = KnowledgeDocumentAdminForm
    list_display = ['id', 'title', 'venue', 'event', 'updated_at']
    list_filter = ['venue', 'event']
    search_fields = ['title', 'content']
    list_display_links = ['id', 'title']
    
    class Media:
        js = ["admin/chained_select.js"]
        
        
@admin.register(KnowledgeChunk)
class KnowledgeChunkAdmin(admin.ModelAdmin):
    """Inspection-only: chunks are generated by KnowledgeService.sync_chunks,
    never hand-authored. Editing content without also recomputing its
    embedding would silently desync the two — search would keep ranking by
    the old meaning while the AI tool returns the new text — so every field
    is read-only rather than trusting an editor to know that."""
    list_display = ['id', 'document', 'chunk_index', 'created_at']
    list_filter = ['document']
    search_fields = ['content']
    list_display_links = ['id', 'document']
    readonly_fields = ['document', 'content', 'embedding', 'chunk_index', 'created_at']

    def has_add_permission(self, request):
        return False