# Generated by Django 5.2.12 on 2026-03-27 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='bookings_bo_user_id_0e7f91_idx'), models.Index(fields=['event'], name='bookings_bo_event_i_87a995_idx'), models.Index(fields=['seat'], name='bookings_bo_seat_id_d5db44_idx')],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key', 'user'), name='unique_idempotency_key_per_user'), models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('seat',), name='unique_confirmed_seat_booking')],
            },
        ),
    ]
