# Generated by Django 5.2.15 on 2026-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_expires_at_booking_retry_count_and_more'),
        ('events', '0002_event_price_event_price_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_confirmed_seat_booking',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_seat_id_d5db44_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='events.seat'),
        ),
        migrations.AddIndex(
            model_name='bookingseat',
            index=models.Index(fields=['booking'], name='bookings_bo_booking_458efe_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingseat',
            index=models.Index(fields=['seat'], name='bookings_bo_seat_id_6b3451_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('booking', 'seat'), name='unique_seat_per_booking'),
        ),
    ]
