# Generated by Django 5.2.16 on 2026-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingseat_unique_seat_claim'),
        ('events', '0002_event_price_event_price_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingseat',
            name='unique_seat_claim',
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('seat',), name='unique_seat_claim'),
        ),
    ]
